// esbuild.config.mjs

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
📦 GENERATED BY ESBUILD
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	entryPoints: ["main.ts"],       // ✅ 진입점: 루트에 있는 main.ts
	bundle: true,
	format: "cjs",
	platform: "node",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",             // ✅ 루트에 main.js 생성
	banner: { js: banner },
	external: [
		"obsidian",
		"electron",
		...builtins
	]
});

console.log("🧱 esbuild.config.mjs 시작됨");

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	console.log("✅ esbuild.build 실행 완료");
}
